# Generated by Django 4.2.13 on 2024-07-08 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_AM', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='username',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
