# Generated by Django 5.0.7 on 2024-07-30 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_AM', '0002_alter_player_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='password_reset_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
