version: '3.8'

services:
  postgres:
    container_name: postgresql
    image: postgres:latest
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - trans
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  transcendence:
    container_name: trans_container
    image: trans_image
    build:
      context: ./trans/.
      dockerfile: Dockerfile
    ports:
      - "80:8000"
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - trans
    env_file:
      - .env
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    volumes:
      - ./trans:/transcendence
    command: "./entry_point.sh"

volumes:
  postgres_data:
    driver: local

networks:
  trans:
    name: trans
    driver: bridge