version: '3.8'

services:
  postgres:
    container_name: postgresql
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - trans
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  django:
    container_name: trans_container
    build:
      context: ./trans/.
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "80:8000"
    depends_on:
      - postgres
    networks:
      - trans
    env_file:
      - .env
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}

volumes:
  postgres_data:
    driver: local

networks:
  trans:
    name: trans
    driver: bridge